### ISSUE TITLE
support for text layer

### ISSUE THREAD

**Issue by raro28** [erayakartuna/pdf-flipbook#1]
I've noticed that there is no way to select the original text.
Now, if I understood the current implementation, a canvas gets drawn from the original div's generated by the PDF.js. 
¿Is there a plan to add a text layer?

**Comment by chrisgraham** [comment]
I had the same issue and unfortunately it was a dealbreaker me because it stops hyperlinks working. pdf.js supports it all, but pdf-flipbook is only taking the canvas and not everything pdf.js layers on top of that to make it interactive.
